version: 2

models:

  - name: stg_accounts
    columns:
      - name: account
        tests:
          - not_null
          - unique

  - name: stg_products
    columns:
      - name: product
        tests:
          - not_null
          - unique

  - name: stg_sales_teams
    columns:
      - name: sales_agent
        tests:
          - not_null

  - name: stg_sales_pipeline
    columns:
      - name: opportunity_id
        tests:
          - not_null
          - unique